"""
Databricks SQL execution client.

Runs generated SQL against the Databricks workspace configured in .env and
returns results as a pandas DataFrame.

Requires in .env:
    DATABRICKS_HOST   = https://community.cloud.databricks.com
    DATABRICKS_TOKEN  = dapiXXXX
    DATABRICKS_CATALOG = hive_metastore          (or main for Unity Catalog)
    DATABRICKS_SCHEMA  = geo_insight
    DATABRICKS_HTTP_PATH = /sql/1.0/warehouses/XXX   ← from cluster/warehouse settings

Setup:
    pip install databricks-sql-connector
    (already in environment.yml if added — see scripts/upload_to_databricks.py)
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

_REQUIRED_ENV = ("DATABRICKS_HOST", "DATABRICKS_TOKEN", "DATABRICKS_HTTP_PATH")


def _check_env() -> None:
    missing = [k for k in _REQUIRED_ENV if not os.environ.get(k)]
    if missing:
        raise EnvironmentError(
            f"Missing required env vars: {missing}\n"
            "Copy .env.example → .env and fill in your Databricks credentials."
        )


def run_sql(sql: str, catalog: str | None = None, schema: str | None = None) -> pd.DataFrame:
    """
    Execute a SQL query against Databricks and return results as a DataFrame.

    Args:
        sql:     SQL string (generated by sql_generator.generate_sql or hand-written).
        catalog: Override DATABRICKS_CATALOG env var.
        schema:  Override DATABRICKS_SCHEMA env var.

    Returns:
        pandas DataFrame with query results.
    """
    from dotenv import load_dotenv
    load_dotenv()
    _check_env()

    try:
        from databricks import sql as dbsql
    except ImportError:
        raise ImportError(
            "databricks-sql-connector not installed.\n"
            "Run: pip install databricks-sql-connector\n"
            "Or add it to environment.yml pip section."
        )

    host = os.environ["DATABRICKS_HOST"].rstrip("/").replace("https://", "")
    token = os.environ["DATABRICKS_TOKEN"]
    http_path = os.environ["DATABRICKS_HTTP_PATH"]
    catalog = catalog or os.environ.get("DATABRICKS_CATALOG", "hive_metastore")
    schema = schema or os.environ.get("DATABRICKS_SCHEMA", "geo_insight")

    with dbsql.connect(
        server_hostname=host,
        http_path=http_path,
        access_token=token,
        catalog=catalog,
        schema=schema,
    ) as conn:
        with conn.cursor() as cursor:
            cursor.execute(sql)
            rows = cursor.fetchall()
            columns = [desc[0] for desc in cursor.description]

    return pd.DataFrame(rows, columns=columns)


def query(user_prompt: str, table_name: str = "geo_insight.master") -> pd.DataFrame:
    """
    End-to-end: natural language → SQL → DataFrame.

    Args:
        user_prompt: Free-text question (e.g. "which countries have gap_score > 0.7 in 2025?")
        table_name:  Fully-qualified Databricks table name.

    Returns:
        DataFrame with results.
    """
    from src.query.sql_generator import generate_sql
    sql = generate_sql(user_prompt, table_name=table_name)
    print(f"Generated SQL:\n{sql}\n")
    return run_sql(sql)
